### ISSUE TITLE
Fix Styling of 404 Page

### ISSUE THREAD

**Issue by CaoRuiming** [CaoRuiming/bpr-wordpress#49]
The 404 page (i.e. the page when the path in the url is invalid like https://brownpoliticalreview.org/404) could be improved. The top of the image seems to overlap with the bottom of the logo of the website's top navbar as shown below.

![Screen Shot 2021-01-28 at 3 37 22 PM](https://user-images.githubusercontent.com/13576351/106195829-b8416880-617e-11eb-912b-e2adb6d4887e.png)

It would be nice to add some margin/space above the image so that it no longer "touches" the logo.

Since this is a very specific thing, it may be reasonable to do [inline styling](https://www.codecademy.com/articles/html-inline-styles) for this case.

**Comment by kangkanjr** [comment]
I will work on this.
