### ISSUE TITLE
Add a Skip Navigation Link to Website

### ISSUE THREAD

**Issue by CaoRuiming** [CaoRuiming/bpr-wordpress#50]
For better accessibility, we should add [skip navigation links](http://web-accessibility.carnegiemuseums.org/code/skip-link/) to the website for screen readers and keyboard-only users.

This would likely have to be added near the top of `head.tpl.php`.

To see a real-world example, you can check out the source html [this website](https://browncsci1430.github.io/webpage/index.html).

**Comment by kangkanjr** [comment]
I will work on this.

**Comment by CaoRuiming** [comment]
Hello @kangkanjr ! I'm glad you're eager to work on this, but all of the "good first issue" tasks for this repository are meant for new Brown Political Review web team members to complete during onboarding in a week or two. You are free to work on this; however, know that we will likely only consider pull requests made by new members during our onboarding process.

**Comment by kangkanjr** [comment]
Ya sure, I will give my version of the solution.

**Comment by CaoRuiming** [comment]
@afishley To make the skip link invisible to everyone except screen readers, you can add the `.sr-only` class (already included Bootstrap 3) to the anchor tag.
