### ISSUE TITLE
Fix Main page column alignment

### ISSUE THREAD

**Issue by n-young** [CaoRuiming/bpr-wordpress#52]
Check main page, scroll down.

**Comment by n-young** [comment]
![Screenshot from 2021-02-08 19-05-38](https://user-images.githubusercontent.com/2057596/107297123-b0b47600-6a40-11eb-9ffb-83f9358c3a1f.png)

**Comment by n-young** [comment]
For the top-left post, you can see that the article title text overflows beyond the article image. We want to constrain the title text to not do that

**Comment by CaoRuiming** [comment]
^^ A possible approach would be to add a wrapper `div` for the title and author line then constraining the width of the wrapper `div` is the CSS to never exceed the width of the images.

**Comment by CaoRuiming** [comment]
Here's a general outline for tackling this task:
- Use the inspect element tool in a web browser to select an article's thumbnail image and check which styling rule is determining its width. You can toggle css rules on and off in real time in the developer tools window. If you can't find a styling rule for an element, looking at the styling for the parent element may help.
- Get the styling rule that sets the width for the thumbnail image and apply it to the `div` that wraps around the article title/link.
- The relevant files for this task may include `col-block.tpl.php`, `_images.scss`, `_front_page.scss`
