### ISSUE TITLE
Fixing search bar accessibility

### ISSUE THREAD

**Issue by n-young** [CaoRuiming/bpr-wordpress#58]
Three action items:
1) Make the type of the search bar input `search`
2) Make the role of the search bar form `search`
3) [Turn off autocomplete](https://www.w3docs.com/snippets/html/how-to-disable-browser-autocomplete-and-autofill-on-html-form-and-input-fields.html) for the search bar form (ignore comment below about suggestions location)

**Comment by n-young** [comment]
Want to somehow make the clicks' suggestions location consistent

**Comment by CaoRuiming** [comment]
@ashley-cai I wanted to explain why these search bar accessibility changes are needed during our meeting, but we ran out of time. So here is some context to these changes:

- making the `type` attribute of the search bar input to search lets the web browser know that the input is for searching with strings -- this gives us some nice features like 'press x to clear the search query' for free (at least in Chrome)
- setting the `role` attribute the parent element of the search part input (i.e. the `form` element) marks the element as a 'search' landmark to screen readers; thus, screen reader users can easily and instantly jump to the search bar
- setting the `autocomplete` option to "off" should disable browsers trying to suggest values to autocomplete in the search bar -- we don't have much control over the location these autocomplete suggestion dropdowns, and autocompletion for search boxes isn't really helpful anyway
